version: "2.1"
services:
  cb1:
    build:
      context: ./docker/couchbase/
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    links:
      - cb2

  cb2:
    build:
      context: ./docker/couchbase/
    ports:
      - 7091:8091